### ISSUE TITLE
[Progressive Trains] Crash on save load or new world after todays hotfix 

### ISSUE THREAD

**Issue by Vexllith** [pacas00/SatisfactoryMods#1]
This is the console output, Only mod loaded

Version: 174506, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000208b5

FactoryGame_CoreUObject_Win64_Shipping!FWeakObjectPtr::Get() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\weakobjectptr.cpp:81]
FactoryGame_CheapTrains_Win64_Shipping!UCheapTrainsLibrary::SetCargoSize() [T:\SF_Modding\U5Modding\Plugins\CheapTrains\Source\CheapTrains\Private\CheapTrainsLibrary.cpp:101]
FactoryGame_CheapTrains_Win64_Shipping!UCheapTrainsLibrary::execSetCargoSize() [T:\SF_Modding\U5Modding\Plugins\CheapTrains\Intermediate\Build\Win64\FactoryGame\Inc\CheapTrains\CheapTrainsLibrary.gen.cpp:58]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2990]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2997]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1157]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1992]
FactoryGame_SML_Win64_Shipping!UModModule::K2_OnLifecycleEvent() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Intermediate\Build\Win64\FactoryGame\Inc\SML\ModModule.gen.cpp:121]
FactoryGame_SML_Win64_Shipping!UModModule::DispatchLifecycleEvent() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Private\Module\ModModule.cpp:43]
FactoryGame_SML_Win64_Shipping!UWorldModuleManager::DispatchLifecycleEvent() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\SML\Plugins\SML\Source\SML\Private\Module\WorldModuleManager.cpp:122]
FactoryGame_SML_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,UWorldModuleManager,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\ar-sml\_work\SatisfactoryModLoader\SatisfactoryModLoader\ue4\lb\win\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:611]
FactoryGame_Engine_Win64_Shipping!TMulticastDelegate<void __cdecl(void),FDefaultDelegateUserPolicy>::Broadcast() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:955]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\unrealengine.cpp:13225]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [d:\ws\sb-211116092526-440\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12430]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12628]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\gameengine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-211116092526-440\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\launch\private\launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by pacas00** [comment]
Hi!
I didn't know the issues section was enabled, shouldnt have been. Support is handled on the modding discord.
In future, can you ping me there for mod support? @PeterCashel#5296 

Given the hotfix, I'd guess SML is going to need updating and then I'll need to make a build that targets the new SML.

**Comment by pacas00** [comment]
Ok, change of plan. Hopefully, the SML guys will have an update ready for us modders in a few hours. After that, might take me a few hours to get it done.
Nothing i can do till then. Closing this for now.
